# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_key', models.CharField(max_length=100)),
                ('analysis_datetime', models.CharField(max_length=50)),
                ('from_datetime', models.CharField(max_length=50)),
                ('end_datetime', models.CharField(max_length=50)),
                ('content_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'email_record',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiAccessAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('source', models.IntegerField(default=0)),
                ('table_content', models.CharField(default='', max_length=5000)),
            ],
            options={
                'db_table': 'monitor_bi_access_analysis',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('indicator', models.CharField(max_length=255, verbose_name='\u6307\u6807indicator')),
                ('indicator_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u6307\u6807\u540d\u79f0')),
                ('is_method', models.IntegerField(default=0, verbose_name='\u65b9\u6cd5\u7c7b\u578b')),
                ('sub_indicator', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u5b50\u6307\u6807indicator')),
                ('sub_indicator_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u5b50\u6307\u6807\u540d\u79f0')),
                ('target_id', models.CharField(blank=True, default='', max_length=255, verbose_name='\u91cd\u53e0\u62a5\u8868ID')),
                ('target_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u91cd\u53e0\u62a5\u8868\u540d\u79f0')),
                ('target_indicator', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u91cd\u53e0\u6307\u6807indicator')),
                ('target_indicator_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u91cd\u53e0\u6307\u6807\u540d\u79f0')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_complicate', models.IntegerField(default=0, verbose_name='\u662f\u5426\u91cd\u53e0\u6307\u6807')),
            ],
            options={
                'db_table': 'monitor_bi_api',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiApiMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('t_id', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('search_time', models.CharField(max_length=100)),
                ('search_type', models.CharField(max_length=100)),
                ('indicator_name', models.CharField(max_length=255)),
                ('indicator_id', models.CharField(max_length=255)),
                ('bi_value', models.CharField(max_length=100)),
                ('compute_value', models.CharField(max_length=100)),
                ('compute_source', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'monitor_bi_api_msg',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('t_type', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u7c7b\u578b')),
                ('is_day', models.IntegerField(default=1, verbose_name='\u662f\u5426\u6309\u5929\u7f13\u5b58')),
                ('is_month', models.IntegerField(default=1, verbose_name='\u662f\u5426\u6309\u6708\u7f13\u5b58')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_cache',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiCacheMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('t_id', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('http_status', models.CharField(max_length=100)),
                ('search_type', models.CharField(max_length=100)),
                ('error_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'monitor_bi_cache_msg',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiColumnTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubes_source', models.CharField(max_length=255, verbose_name='CUBES')),
                ('cubes_name', models.CharField(blank=True, max_length=255, verbose_name='CUBES\u540d\u79f0')),
                ('column_source_params', models.CharField(blank=True, max_length=2000, verbose_name='column\u8bf7\u6c42\u53c2\u6570')),
                ('table_source_params', models.CharField(blank=True, max_length=2000, verbose_name='table\u8bf7\u6c42\u53c2\u6570')),
                ('column_url', models.CharField(blank=True, max_length=255, verbose_name='column\u8bf7\u6c42url')),
                ('table_url', models.CharField(blank=True, max_length=255, verbose_name='table\u8bf7\u6c42url')),
                ('cookies_url', models.CharField(blank=True, max_length=255, verbose_name='cookies\u8bf7\u6c42url')),
                ('login_params', models.CharField(blank=True, max_length=50, verbose_name='login\u53c2\u6570')),
                ('cookies', models.CharField(blank=True, max_length=50, verbose_name='cookies')),
                ('is_login', models.IntegerField(default=0, verbose_name='\u662f\u5426login')),
                ('is_cookies', models.IntegerField(default=0, verbose_name='\u662f\u5426cookies')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_column_table',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('t_type', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u7c7b\u578b')),
                ('is_personnel', models.IntegerField(default=0, verbose_name='\u662f\u5426\u4eba\u6548\u62a5\u8868')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_data',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiDataMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('t_id', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('indicator_name', models.CharField(max_length=255)),
                ('search_time', models.CharField(max_length=100)),
                ('search_type', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=100)),
                ('deviation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'monitor_bi_data_msg',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiEnumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('t_name', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5e93\u8868\u540d\u79f0')),
                ('t_up_col', models.CharField(blank=True, default='', max_length=50, verbose_name='\u65f6\u95f4\u5b57\u6bb5')),
                ('col_name', models.CharField(blank=True, default='', max_length=50, verbose_name='\u679a\u4e3e\u5b57\u6bb5\u540d\u79f0')),
                ('col_value', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u679a\u4e3e\u5b57\u6bb5\u5217\u8868')),
                ('time_type', models.IntegerField(default=1, verbose_name='\u65f6\u95f4\u7c7b\u578b')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_enumeration',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiEnumerationMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('db_mname', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=255)),
                ('t_col', models.CharField(max_length=100)),
                ('t_value', models.CharField(max_length=1000)),
                ('error_value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'monitor_bi_enumeration_msg',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=100, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=100, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('t_type', models.CharField(blank=True, default='', max_length=100, verbose_name='\u62a5\u8868\u7c7b\u578b')),
                ('history_error', models.IntegerField(default=0, verbose_name='\u5386\u53f2\u9519\u8bef')),
                ('continuous_error', models.IntegerField(default=0, verbose_name='\u8fde\u7eed\u9519\u8bef')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_interface',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiInterfaceMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('t_name', models.CharField(max_length=255)),
                ('t_id', models.CharField(max_length=100)),
                ('http_status', models.CharField(max_length=50)),
                ('search_type', models.CharField(max_length=50)),
                ('monitor_type', models.CharField(max_length=50)),
                ('history_error', models.CharField(max_length=50)),
                ('continuous_error', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'monitor_bi_interface_msg',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiNginxLogWeekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('analysis_type', models.IntegerField(default=0)),
                ('analysis_key', models.CharField(default='', max_length=20)),
                ('analysis_api', models.CharField(default='/api/dashboard?', max_length=200)),
                ('api_count', models.IntegerField(default=0)),
                ('percent', models.FloatField()),
                ('average_delay_microseconds', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'monitor_bi_nginx_log_week_report',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiNoteWorthyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('source', models.IntegerField(default=0)),
                ('access_datetime', models.CharField(default='', max_length=50)),
                ('method', models.IntegerField(default=0)),
                ('report_name', models.CharField(max_length=60)),
                ('report_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=50)),
                ('delay_microseconds', models.FloatField(default=0)),
                ('parameters', models.CharField(max_length=500)),
                ('department_name', models.CharField(max_length=20)),
                ('api_key', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'monitor_bi_noteworthy_log',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiScriptsMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('alert_msg', models.CharField(max_length=255)),
                ('script_name', models.CharField(max_length=255)),
                ('script_status', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=50)),
                ('monitor_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'monitor_bi_scripts_msg',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiSourceGroupby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='\u6307\u6807ID')),
                ('bi_job_id', models.CharField(max_length=100, verbose_name='\u6e05\u6d17\u811a\u672c\u540d\u79f0')),
                ('origin_field', models.CharField(blank=True, max_length=100, verbose_name='\u6e90\u5b57\u6bb5')),
                ('origin_db', models.CharField(blank=True, max_length=50, verbose_name='\u6e90\u6570\u636e\u5e93')),
                ('origin_sel', models.CharField(blank=True, max_length=100, verbose_name='\u6e90\u6570\u636e\u5b57\u6bb5')),
                ('origin_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u6e90\u6570\u636eSQL')),
                ('origin_time_type', models.IntegerField(default=0, verbose_name='\u6e90\u8868\u65f6\u95f4\u7c7b\u578b')),
                ('target_field', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u6807\u5b57\u6bb5')),
                ('target_db', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807\u6570\u636e\u5e93')),
                ('target_sel', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u6807\u6570\u636e\u5b57\u6bb5')),
                ('target_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u76ee\u6807\u6570\u636eSQL')),
                ('target_time_type', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u8868\u65f6\u95f4\u7c7b\u578b')),
                ('middle_first_db', models.CharField(blank=True, max_length=50, verbose_name='\u4e2d\u95f4\u8868\u4e00\u6570\u636e\u5e93')),
                ('middle_first_sel', models.CharField(blank=True, max_length=100, verbose_name='\u4e2d\u95f4\u8868\u4e00\u6570\u636e\u5b57\u6bb5')),
                ('middle_first_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u4e2d\u95f4\u8868\u4e00\u6570\u636eSQL')),
                ('middle_first_time_type', models.IntegerField(default=0, verbose_name='\u4e2d\u95f4\u8868\u4e00\u65f6\u95f4\u7c7b\u578b')),
                ('middle_second_db', models.CharField(blank=True, max_length=50, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u6570\u636e\u5e93')),
                ('middle_second_sel', models.CharField(blank=True, max_length=100, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u6570\u636e\u5b57\u6bb5')),
                ('middle_second_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u6570\u636eSQL')),
                ('middle_second_time_type', models.IntegerField(default=0, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u65f6\u95f4\u7c7b\u578b')),
                ('is_complicate', models.IntegerField(default=0, verbose_name='\u662f\u5426\u8de8\u5e93')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_source_groupby',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('t_id', models.CharField(max_length=50, verbose_name='\u5e93\u8868')),
                ('t_name', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5e93\u8868\u540d\u79f0')),
                ('t_column', models.CharField(blank=True, default='', max_length=50, verbose_name='\u65f6\u95f4\u5b57\u6bb5')),
                ('time_type', models.IntegerField(default=1, verbose_name='\u65f6\u95f4\u7c7b\u578b')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_tables',
            },
        ),
        migrations.CreateModel(
            name='MonitorBiUvPv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubes_source', models.CharField(max_length=255, verbose_name='CUBES')),
                ('cubes_name', models.CharField(blank=True, max_length=255, verbose_name='CUBES\u540d\u79f0')),
                ('ignore_user_email', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u4e0d\u76d1\u63a7\u7528\u6237email')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
            options={
                'db_table': 'monitor_bi_uv_pv',
            },
        ),
    ]
