# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('analysis_type', models.IntegerField(default=0)),
                ('analysis_key', models.CharField(default='', max_length=20)),
                ('analysis_api', models.CharField(default='/api/dashboard?', max_length=200)),
                ('api_count', models.IntegerField(default=0)),
                ('percent', models.FloatField()),
                ('average_delay_time', models.FloatField(default=0)),
            ],
            options={
                'db_table': 't_interval_report',
            },
        ),
    ]
