# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalreport',
            name='start_date',
            field=models.DateField(),
        ),
    ]
