# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorbiaccessanalysis',
            old_name='source',
            new_name='access_source',
        ),
        migrations.RenameField(
            model_name='monitorbilogweekreport',
            old_name='source',
            new_name='access_source',
        ),
        migrations.RenameField(
            model_name='monitorbinoteworthylog',
            old_name='source',
            new_name='access_source',
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 15, 42, 35, 375000)),
        ),
    ]
