# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0002_monitorbisourcedatamsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorBiSourceGroupByMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('indicator_name', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=100)),
                ('target_name', models.CharField(max_length=50)),
                ('search_time', models.CharField(max_length=50)),
                ('col_value', models.CharField(max_length=50)),
                ('source_number', models.CharField(max_length=50)),
                ('target_number', models.CharField(max_length=50)),
                ('devi_reason', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'monitor_bi_source_groupby_msg',
            },
        ),
    ]
