# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0002_auto_20171114_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiAccessAnalysis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_timestamp', models.IntegerField(default=0)),
                ('end_timestamp', models.IntegerField(default=0)),
                ('source', models.IntegerField(default=0)),
                ('kind', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
            ],
            options={
                'db_table': 't_bi_access_analysis',
            },
        ),
    ]
