# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0003_biaccessanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervalreport',
            old_name='end_date',
            new_name='end_timestamp',
        ),
        migrations.RenameField(
            model_name='intervalreport',
            old_name='start_date',
            new_name='from_timestamp',
        ),
    ]
