# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0003_monitorbisourcegroupbymsg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorbisourcegroupbymsg',
            old_name='devi_reason',
            new_name='deviation',
        ),
    ]
