# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0004_auto_20171115_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteWorthyLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_timestamp', models.IntegerField(default=0)),
                ('method', models.IntegerField(default=0)),
                ('report_name', models.CharField(max_length=60)),
                ('report_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=50)),
                ('delay_microseconds', models.FloatField(default=0)),
                ('parameters', models.CharField(max_length=500)),
                ('department_name', models.CharField(max_length=20)),
                ('api_key', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_noteworthy_log',
            },
        ),
    ]
