# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0005_monitorcubescolumnmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorCubesTablesMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('db_name', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=100)),
                ('http_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'monitor_cubes_table_msg',
            },
        ),
    ]
