# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0005_noteworthylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('analysis_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekReportItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('week_report_id', models.IntegerField()),
                ('analysis_type', models.IntegerField(default=0)),
                ('analysis_key', models.CharField(default='', max_length=20)),
                ('analysis_api', models.CharField(default='/api/dashboard?', max_length=200)),
                ('api_count', models.IntegerField(default=0)),
                ('percent', models.FloatField()),
                ('average_delay_time', models.FloatField(default=0)),
            ],
            options={
                'db_table': 't_week_report_item',
            },
        ),
        migrations.DeleteModel(
            name='IntervalReport',
        ),
    ]
