# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0007_auto_20171124_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorbicachemsg',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 15, 56, 10, 705000)),
        ),
        migrations.AlterField(
            model_name='monitorbicachemsg',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 24, 15, 56, 10, 705000)),
        ),
    ]
