# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0008_auto_20171122_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteworthylog',
            name='source',
            field=models.IntegerField(default=0),
        ),
    ]
