# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0008_auto_20171124_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('indicator', models.CharField(max_length=255, verbose_name='\u6307\u6807indicator')),
                ('indicator_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u6307\u6807\u540d\u79f0')),
                ('is_method', models.IntegerField(default=0, verbose_name='\u65b9\u6cd5\u7c7b\u578b')),
                ('sub_indicator', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u5b50\u6307\u6807indicator')),
                ('sub_indicator_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u5b50\u6307\u6807\u540d\u79f0')),
                ('target_id', models.CharField(blank=True, default='', max_length=255, verbose_name='\u91cd\u53e0\u62a5\u8868ID')),
                ('target_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u91cd\u53e0\u62a5\u8868\u540d\u79f0')),
                ('target_indicator', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u91cd\u53e0\u6307\u6807indicator')),
                ('target_indicator_name', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u91cd\u53e0\u6307\u6807\u540d\u79f0')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('is_complicate', models.IntegerField(default=0, verbose_name='\u662f\u5426\u91cd\u53e0\u6307\u6807')),
            ],
        ),
        migrations.CreateModel(
            name='api_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('search_time', models.CharField(blank=True, default='', max_length=100, verbose_name='\u67e5\u8be2\u65f6\u95f4')),
                ('search_type', models.CharField(blank=True, default='', max_length=100, verbose_name='\u67e5\u8be2\u7c7b\u578b')),
                ('indicator_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u6307\u6807\u540d\u79f0')),
                ('indicator_id', models.CharField(default='', max_length=255, verbose_name='\u6307\u6807Indicator')),
                ('bi_value', models.CharField(blank=True, default='', max_length=100, verbose_name='BI\u663e\u793a\u6307\u6807\u503c')),
                ('compute_value', models.CharField(blank=True, default='', max_length=100, verbose_name='\u8ba1\u7b97\u6240\u5f97\u6307\u6807\u503c')),
                ('compute_source', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u8ba1\u7b97\u6570\u636e\u6765\u6e90')),
            ],
        ),
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('t_type', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u7c7b\u578b')),
                ('is_day', models.IntegerField(default=1, verbose_name='\u662f\u5426\u6309\u5929\u7f13\u5b58')),
                ('is_month', models.IntegerField(default=1, verbose_name='\u662f\u5426\u6309\u6708\u7f13\u5b58')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='column_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubes_source', models.CharField(max_length=255, verbose_name='CUBES')),
                ('cubes_name', models.CharField(blank=True, max_length=255, verbose_name='CUBES\u540d\u79f0')),
                ('column_source_params', models.CharField(blank=True, max_length=2000, verbose_name='column\u8bf7\u6c42\u53c2\u6570')),
                ('table_source_params', models.CharField(blank=True, max_length=2000, verbose_name='table\u8bf7\u6c42\u53c2\u6570')),
                ('column_url', models.CharField(blank=True, max_length=255, verbose_name='column\u8bf7\u6c42url')),
                ('table_url', models.CharField(blank=True, max_length=255, verbose_name='table\u8bf7\u6c42url')),
                ('cookies_url', models.CharField(blank=True, max_length=255, verbose_name='cookies\u8bf7\u6c42url')),
                ('login_params', models.CharField(blank=True, max_length=50, verbose_name='login\u53c2\u6570')),
                ('cookies', models.CharField(blank=True, max_length=50, verbose_name='cookies')),
                ('is_login', models.IntegerField(default=0, verbose_name='\u662f\u5426login')),
                ('is_cookies', models.IntegerField(default=0, verbose_name='\u662f\u5426cookies')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('t_type', models.CharField(blank=True, default='', max_length=255, verbose_name='\u62a5\u8868\u7c7b\u578b')),
                ('is_personnel', models.IntegerField(default=0, verbose_name='\u662f\u5426\u4eba\u6548\u62a5\u8868')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('t_name', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5e93\u8868\u540d\u79f0')),
                ('t_up_col', models.CharField(blank=True, default='', max_length=50, verbose_name='\u65f6\u95f4\u5b57\u6bb5')),
                ('col_name', models.CharField(blank=True, default='', max_length=50, verbose_name='\u679a\u4e3e\u5b57\u6bb5\u540d\u79f0')),
                ('col_value', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u679a\u4e3e\u5b57\u6bb5\u5217\u8868')),
                ('time_type', models.IntegerField(default=1, verbose_name='\u65f6\u95f4\u7c7b\u578b')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=100, verbose_name='\u62a5\u8868ID')),
                ('t_name', models.CharField(blank=True, default='', max_length=100, verbose_name='\u62a5\u8868\u540d\u79f0')),
                ('t_type', models.CharField(blank=True, default='', max_length=100, verbose_name='\u62a5\u8868\u7c7b\u578b')),
                ('history_error', models.IntegerField(default=0, verbose_name='\u5386\u53f2\u9519\u8bef')),
                ('continuous_error', models.IntegerField(default=0, verbose_name='\u8fde\u7eed\u9519\u8bef')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='source_groupby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='\u6307\u6807ID')),
                ('bi_job_id', models.CharField(max_length=100, verbose_name='\u6e05\u6d17\u811a\u672c\u540d\u79f0')),
                ('origin_field', models.CharField(blank=True, max_length=100, verbose_name='\u6e90\u5b57\u6bb5')),
                ('origin_db', models.CharField(blank=True, max_length=50, verbose_name='\u6e90\u6570\u636e\u5e93')),
                ('origin_sel', models.CharField(blank=True, max_length=100, verbose_name='\u6e90\u6570\u636e\u5b57\u6bb5')),
                ('origin_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u6e90\u6570\u636eSQL')),
                ('origin_time_type', models.IntegerField(default=0, verbose_name='\u6e90\u8868\u65f6\u95f4\u7c7b\u578b')),
                ('target_field', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u6807\u5b57\u6bb5')),
                ('target_db', models.CharField(blank=True, max_length=50, verbose_name='\u76ee\u6807\u6570\u636e\u5e93')),
                ('target_sel', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u6807\u6570\u636e\u5b57\u6bb5')),
                ('target_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u76ee\u6807\u6570\u636eSQL')),
                ('target_time_type', models.IntegerField(default=0, verbose_name='\u76ee\u6807\u8868\u65f6\u95f4\u7c7b\u578b')),
                ('middle_first_db', models.CharField(blank=True, max_length=50, verbose_name='\u4e2d\u95f4\u8868\u4e00\u6570\u636e\u5e93')),
                ('middle_first_sel', models.CharField(blank=True, max_length=100, verbose_name='\u4e2d\u95f4\u8868\u4e00\u6570\u636e\u5b57\u6bb5')),
                ('middle_first_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u4e2d\u95f4\u8868\u4e00\u6570\u636eSQL')),
                ('middle_first_time_type', models.IntegerField(default=0, verbose_name='\u4e2d\u95f4\u8868\u4e00\u65f6\u95f4\u7c7b\u578b')),
                ('middle_second_db', models.CharField(blank=True, max_length=50, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u6570\u636e\u5e93')),
                ('middle_second_sel', models.CharField(blank=True, max_length=100, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u6570\u636e\u5b57\u6bb5')),
                ('middle_second_sql', models.CharField(blank=True, max_length=3000, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u6570\u636eSQL')),
                ('middle_second_time_type', models.IntegerField(default=0, verbose_name='\u4e2d\u95f4\u8868\u4e8c\u65f6\u95f4\u7c7b\u578b')),
                ('is_complicate', models.IntegerField(default=0, verbose_name='\u662f\u5426\u8de8\u5e93')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=50, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('t_id', models.CharField(max_length=50, verbose_name='\u5e93\u8868')),
                ('t_name', models.CharField(blank=True, default='', max_length=200, verbose_name='\u5e93\u8868\u540d\u79f0')),
                ('t_column', models.CharField(blank=True, default='', max_length=50, verbose_name='\u65f6\u95f4\u5b57\u6bb5')),
                ('time_type', models.IntegerField(default=1, verbose_name='\u65f6\u95f4\u7c7b\u578b')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='uv_pv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubes_source', models.CharField(max_length=255, verbose_name='CUBES')),
                ('cubes_name', models.CharField(blank=True, max_length=255, verbose_name='CUBES\u540d\u79f0')),
                ('ignore_user_email', models.CharField(blank=True, default='', max_length=1000, verbose_name='\u4e0d\u76d1\u63a7\u7528\u6237email')),
                ('is_delete', models.IntegerField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
            ],
        ),
        migrations.RemoveField(
            model_name='monitorbicachemsg',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monitorbicachemsg',
            name='updated_at',
        ),
    ]
