# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0009_noteworthylog_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biaccessanalysis',
            name='average',
        ),
        migrations.RemoveField(
            model_name='biaccessanalysis',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='biaccessanalysis',
            name='num',
        ),
        migrations.RemoveField(
            model_name='biaccessanalysis',
            name='percent',
        ),
        migrations.AddField(
            model_name='biaccessanalysis',
            name='table_content',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
