# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0009_auto_20171124_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='api_msg',
        ),
        migrations.AlterModelTable(
            name='api',
            table='monitor_bi_api',
        ),
        migrations.AlterModelTable(
            name='cache',
            table='monitor_bi_cache',
        ),
        migrations.AlterModelTable(
            name='column_table',
            table='monitor_bi_column_table',
        ),
        migrations.AlterModelTable(
            name='data',
            table='monitor_bi_data',
        ),
        migrations.AlterModelTable(
            name='enumeration',
            table='monitor_bi_enumeration',
        ),
        migrations.AlterModelTable(
            name='interface',
            table='monitor_bi_interface',
        ),
        migrations.AlterModelTable(
            name='source_groupby',
            table='monitor_bi_source_groupby',
        ),
        migrations.AlterModelTable(
            name='tables',
            table='monitor_bi_tables',
        ),
        migrations.AlterModelTable(
            name='uv_pv',
            table='monitor_bi_uv_pv',
        ),
    ]
