# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0010_auto_20171124_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='api',
            new_name='MonitorBiApi',
        ),
        migrations.RenameModel(
            old_name='cache',
            new_name='MonitorBiCache',
        ),
        migrations.RenameModel(
            old_name='column_table',
            new_name='MonitorBiColumnTable',
        ),
        migrations.RenameModel(
            old_name='data',
            new_name='MonitorBiData',
        ),
        migrations.RenameModel(
            old_name='enumeration',
            new_name='MonitorBiEnumeration',
        ),
        migrations.RenameModel(
            old_name='interface',
            new_name='MonitorBiInterface',
        ),
        migrations.RenameModel(
            old_name='source_groupby',
            new_name='MonitorBiSourceGroupby',
        ),
        migrations.RenameModel(
            old_name='tables',
            new_name='MonitorBiTables',
        ),
        migrations.RenameModel(
            old_name='uv_pv',
            new_name='MonitorBiUvPv',
        ),
    ]
