# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0011_auto_20171124_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorBiDataMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('t_id', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('indicator_name', models.CharField(max_length=255)),
                ('search_time', models.CharField(max_length=100)),
                ('search_type', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=100)),
                ('deviation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'monitor_bi_data_msg',
            },
        ),
    ]
