# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0012_monitorbidatamsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorBiEnumerationMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('db_mname', models.CharField(max_length=100)),
                ('t_name', models.CharField(max_length=255)),
                ('t_col', models.CharField(max_length=100)),
                ('t_value', models.CharField(max_length=1000)),
                ('error_value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'monitor_bi_enumeration_msg',
            },
        ),
    ]
