# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0012_auto_20171123_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorBiCacheMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=255)),
                ('t_name', models.CharField(max_length=255)),
                ('http_status', models.CharField(max_length=100)),
                ('search_type', models.CharField(max_length=100)),
                ('error_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(max_length=255)),
                ('updated_at', models.DateTimeField(max_length=100)),
            ],
            options={
                'db_table': 'monitor_bi_cache_msg',
            },
        ),
        migrations.AlterModelTable(
            name='weekreport',
            table='t_week_report',
        ),
    ]
