# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0013_auto_20171123_1816'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='biaccessanalysis',
            table='bi_access_analysis',
        ),
        migrations.AlterModelTable(
            name='houranalysis',
            table='hour_analysis',
        ),
        migrations.AlterModelTable(
            name='noteworthylog',
            table='noteworthy_log',
        ),
        migrations.AlterModelTable(
            name='weekreport',
            table='week_report',
        ),
        migrations.AlterModelTable(
            name='weekreportitem',
            table='week_report_item',
        ),
    ]
