# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0013_monitorbienumerationmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorBiInterfaceMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recorder_id', models.IntegerField(default=0)),
                ('t_name', models.CharField(max_length=255)),
                ('t_id', models.CharField(max_length=100)),
                ('http_status', models.CharField(max_length=50)),
                ('search_type', models.CharField(max_length=50)),
                ('monitor_type', models.CharField(max_length=50)),
                ('history_error', models.CharField(max_length=50)),
                ('continuous_error', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'monitor_bi_interface_msg',
            },
        ),
    ]
