# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_monitor_app', '0014_auto_20171123_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorbicachemsg',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 18, 41, 37, 990000)),
        ),
        migrations.AlterField(
            model_name='monitorbicachemsg',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 18, 41, 37, 990000)),
        ),
    ]
